services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "80:80"
    networks:
      - my-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
